### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AhmedBaset** [devaryakjha/fcm_notifications_nextjs#1]
Is there a way to not hardcode this config in the SW file?
https://github.com/devaryakjha/fcm_notifications_nextjs/blob/22e7af9f5da58ca795fcadb431e97b4cc2c2b4c3/public/firebase-messaging-sw.js#L6-L14

I know that process.env is a part of Node.js so It's not available in the vanilla javascript. but I'm looking for a way to not include them in the repo. to easily update them on deployment.

**Comment by devaryakjha** [comment]
@A7med3bdulBaset I don't believe there is a way to use env variables here, but if you're worried about exposing your apiKeys then you might wanna check [this](https://stackoverflow.com/a/37484053/22182788) out if you haven't already. 

But if all you want to do is to be able to provide config based on different envs then [this](https://stackoverflow.com/a/76818218/18253567) answer might help you out.

**Comment by AhmedBaset** [comment]
I'm not asking about the security, anyway these keys must be shipped to the client. I want to do that to make them separate from the repo and easily update them.

some solution came to my mind now.
I think we can create a GET request in `app/firebase-messaging-sw.js/route.ts like so
```ts
export async function GET() {
  const template = await fs.readFile(path.join(path.cwd(), 'src', 'utils', 'firebase-messaging-sw.js`), "utf-8")
  const firebaseConfig = `
     const firebaseConfig = {
        apiKey: ${process.env.NEXT_PUBLIC_FIREBASE_API_KEY},
        authDomain: ${process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN},
        projectId: ${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID},
        storageBucket: ${process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET},
        messagingSenderId: ${process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID},
        appId: ${process.env.NEXT_PUBLIC_FIREBASE_APP_ID},
     }
  `
  const swFile = template.replace("<PUT_THE_CONFIG_HERE>", firebaseConfig)
  return Response(swFile)
}
```
or with pre-build script
